config/routes.rb
Rails.application.routes.draw do

  get 'landing/buy1', to: 'landing#buy1'
  get 'landing/buy2', to: 'landing#buy2'
  get 'landing/buy3', to: 'landing#buy3'
  get 'landing/buy4', to: 'landing#buy4'
  get 'landing/sell1', to: 'landing#sell1'
  get 'landing/sell2', to: 'landing#sell2'
  get 'landing/sell3', to: 'landing#sell3'
  get 'landing/sell4', to: 'landing#sell4'
  post 'landing', action: :create1, controller: 'landing'
  post 'landing2', action: :create2, controller: 'landing'
  post 'landing3', action: :create3, controller: 'landing'
  post 'landing4', action: :create4, controller: 'landing'
  post 'landing5', action: :create5, controller: 'landing'
  post 'landing6', action: :create6, controller: 'landing'
  post 'landing7', action: :create7, controller: 'landing'
  post 'landing8', action: :create8, controller: 'landing'
  put 'landing/:id', to: 'landing#update1'
  put 'landing', to: 'landing#index'
  get 'landing', to: 'landing#index'
  get 'landing2', to: 'landing#index2'
  get 'landing3', to: 'landing#index3'
  get 'landing4', to: 'landing#index4'
  get 'landing5', to: 'landing#index5'
  get 'landing6', to: 'landing#index6'
  get 'landing7', to: 'landing#index7'
  get 'landing8', to: 'landing#index8'
  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendars', to: 'calendar#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'calendar#events', as: 'events', calendar_id: /[^\/]+/
  put 'tasks/:id', to: 'tasks#update1'
  get 'matches', to: 'matches#index'
  get 'contacts/buyers', to: 'contacts#buyersindex'
  get 'contacts/sellers', to: 'contacts#sellersindex'
  get 'contacts/closed', to: 'contacts#closed'
  put 'contacts/:id', action: 'convert', controller: 'contacts', as: 'convert_contact'
  get 'leads/buyers', to: 'leads#buyersindex'
  get 'leads/sellers', to: 'leads#sellersindex'
  get 'logout_session'  => 'authentications#destroy'
  get 'opportunities/buyers', to: 'opportunities#buyersindex'
  get 'opportunities/sellers', to: 'opportunities#sellersindex'
  get 'leadcontacts', to: 'leadcontacts#index'
  get '/leadcontacts/new', to: 'leadcontacts#new'
  post 'leadcontacts', action: :create, controller: 'leadcontacts'
  delete 'destroy_multiple_leadcontacts', action: 'destroy_multiple', controller: 'leadcontacts'

  resources :contacts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: %i[get post]
      get :redraw
      get :versions
      delete 'destroy_multiple'
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: %i[get post]
      get :redraw
      get :versions
      get :autocomplete_account_name
      delete 'destroy_multiple'
    end
    member do
      get :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put :attach
      match :promote, via: %i[patch put]
      put :reject
    end
  end
end

app/models/account.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
# == Schema Information
#
# Table name: accounts
#
#  id              :integer         not null, primary key
#  user_id         :integer
#  assigned_to     :integer
#  name            :string(64)      default(""), not null
#  access          :string(8)       default("Public")
#  website         :string(64)
#  toll_free_phone :string(32)
#  phone           :string(32)
#  fax             :string(32)
#  deleted_at      :datetime
#  created_at      :datetime
#  updated_at      :datetime
#  email           :string(64)
#  background_info :string(255)
#  rating          :integer         default(0), not null
#  category        :string(32)
#

class Account < ActiveRecord::Base
  belongs_to :user
  belongs_to :assignee, class_name: "User", foreign_key: :assigned_to
  has_many :account_contacts, dependent: :destroy
  has_many :contacts, -> { distinct }, through: :account_contacts
  has_many :account_opportunities, dependent: :destroy
  has_many :opportunities, -> { order("opportunities.id DESC").distinct }, through: :account_opportunities
  has_many :tasks, as: :asset, dependent: :destroy # , :order => 'created_at DESC'
  has_one :billing_address, -> { where(address_type: "Billing") }, dependent: :destroy, as: :addressable, class_name: "Address"
  has_one :shipping_address, -> { where(address_type: "Shipping") }, dependent: :destroy, as: :addressable, class_name: "Address"
  has_many :addresses, dependent: :destroy, as: :addressable, class_name: "Address" # advanced search uses this
  has_many :emails, as: :mediator

  serialize :subscribed_users, Set

  accepts_nested_attributes_for :billing_address,  allow_destroy: true, reject_if: proc { |attributes| Address.reject_address(attributes) }
  accepts_nested_attributes_for :shipping_address, allow_destroy: true, reject_if: proc { |attributes| Address.reject_address(attributes) }

  scope :state, ->(filters) {
    where('category IN (?)' + (filters.delete('other') ? ' OR category IS NULL' : ''), filters)
  }
  scope :created_by,  ->(user) { where(user_id: user.id) }
  scope :assigned_to, ->(user) { where(assigned_to: user.id) }

  scope :text_search, ->(query) { ransack('name_or_email_cont' => query).result }

  scope :visible_on_dashboard, ->(user) {
    # Show accounts which either belong to the user and are unassigned, or are assigned to the user
    where('(user_id = :user_id AND assigned_to IS NULL) OR assigned_to = :user_id', user_id: user.id)
  }

  scope :by_name, -> { order(:name) }

  uses_user_permissions
  acts_as_commentable
  uses_comment_extensions
  acts_as_taggable_on :tags
  has_paper_trail class_name: 'Version', ignore: [:subscribed_users]
  has_fields
  exportable
  sortable by: ["name ASC", "rating DESC", "created_at DESC", "updated_at DESC"], default: "created_at DESC"

  has_ransackable_associations %w[contacts opportunities tags activities emails addresses comments tasks]
  ransack_can_autocomplete

  validates_presence_of :name, message: :missing_account_name
  # validates_uniqueness_of :name, scope: :deleted_at, if: -> { Setting.require_unique_account_names }
  validates :rating, inclusion: { in: 0..5 }, allow_blank: true
  validates :category, inclusion: { in: proc { Setting.unroll(:account_category).map { |s| s.last.to_s } } }, allow_blank: true
  validate :users_for_shared_access

  before_save :nullify_blank_category

  # Default values provided through class methods.
  #----------------------------------------------------------------------------
  def self.per_page
    20
  end

  # Extract last line of billing address and get rid of numeric zipcode.
  #----------------------------------------------------------------------------
  def location
    return "" unless self[:billing_address]
    location = self[:billing_address].strip.split("\n").last
    location.gsub(/(^|\s+)\d+(:?\s+|$)/, " ").strip if location
  end

  # Attach given attachment to the account if it hasn't been attached already.
  #----------------------------------------------------------------------------
  def attach!(attachment)
    unless send("#{attachment.class.name.downcase}_ids").include?(attachment.id)
      send(attachment.class.name.tableize) << attachment
    end
  end

  # Discard given attachment from the account.
  #----------------------------------------------------------------------------
  def discard!(attachment)
    if attachment.is_a?(Task)
      attachment.update_attribute(:asset, nil)
    else # Contacts, Opportunities
      send(attachment.class.name.tableize).delete(attachment)
    end
  end

  # Class methods.
  #----------------------------------------------------------------------------
  def self.create_or_select_for(model, params)
    if params[:id].present?
      account = Account.find(params[:id])
    else
      account = Account.new(params)
      if account.access != "Lead" || model.nil?
        account.save
      else
        account.save_with_model_permissions(model)
      end
    end
    account
  end

  private

  # Make sure at least one user has been selected if the account is being shared.
  #----------------------------------------------------------------------------
  def users_for_shared_access
    errors.add(:access, :share_account) if self[:access] == "Shared" && !permissions.any?
  end

  def nullify_blank_category
    self.category = nil if category.blank?
  end

  ActiveSupport.run_load_hooks(:fat_free_crm_account, self)
end

app/controllers/leadcontacts_controller.rb
class LeadcontactsController < ApplicationController
  def index
    @leads = Contact.where(:islead=>"true")
  end
  def new
    @lead = Contact.new
  end
  def create
    @lead = Contact.create (lead_params)
    respond_to do |format|
      if @lead.save
        format.html { redirect_to leadcontacts_path }
        format.js { }
      else
        format.html { flash.now[:alert] = "Not done"
        render "new"
        }
        format.js { render :js=>'alert("not done");' }
      end
    end
  end
  def destroy_multiple
    Contact.where(id: params[:contact_ids]).destroy_all
    respond_to do |format|
      format.html { redirect_to leadcontacts_url }
      format.json { head :no_content }
    end
  end
  private
  def lead_params
    params.require(:contact).permit(:first_name, :last_name, :address, :postalcode, :unit, :desireddeal, :extrainfo, :phone, :email, :source, :buysell, :leadstatus, :city, :neighbourhood, :propertytype, :price, :bedrooms, :bathrooms, :buildingage, :islead)
  end
end

app/helpers/leadcontacts_helper.rb
module LeadcontactsHelper
end

app/views/leadcontacts/index.html.erb
<div class="title">
  <span>
    Leads
  </span>
  <%= link_to 'New Lead', '/leadcontacts/new' %>
</div>
<%# app/views/leads/_list.html.erb %>
<div id="filterrific_results">
  <style>
    #filter{
      width:100%;
    }
    #filter td,th{
      border:thin black solid;
    }
    #filter th{
      font-size:1.2em;
    }
    #filter td{
      text-align: right;
      padding-right:5px;
    }
    .tablecss td{
      text-align: center !important;
      font-size: 1.3em;
    }
    .bulkbutton{
      color:white;
      display:inline-block;
      float:right;
      padding: 5px;
      margin: 5px;
      border-radius: 4px;
      box-shadow: 2px 2px 3px #aaa;
    }
    #delsubmit{
      background-color: red;
    }
    #checkAll{
      background-color: dodgerblue;
    }
  </style>
  <div>
    <% if current_user.admin? %>
        <%# page_entries_info @leads %>(s)
    <% end %>
    <!--<div class="bulkbutton" id="bulkconvert" style="background-color:green;">Convert Selected</div>-->
  </div>

  <br>
  <%= form_tag destroy_multiple_leadcontacts_path, method: :delete do %>
      <table class="tablecss" id="filter">
        <tr style="text-align: center;">
          <th>Lead Status</th>
          <th>Name</th>
          <th>Buyer/Seller</th>
          <th>Property Type</th>
          <th>Area</th>
          <th>Price</th>
          <th>Assigned To</th>
          <th>Registered at</th>
          <th>Rating</th>
          <th>Delete</th>
        </tr>
        <% @leads.each do |lead| %>
            <% if current_user.admin? %>
                <tr>
                  <td id="leadcolor"><%= lead.leadstatus.capitalize if lead.leadstatus.present? %></td>
                  <td><%= link_to(lead.full_name, contact_path(lead)) %></td>
                  <td><%= lead.buysell if lead.buysell.present? %></td>
                  <td><%= lead.propertytype %></td>
                  <td><%= lead.city %></td>
                  <td>
                    <% if lead.price.present? %>
                        $<%= number_with_delimiter(lead.price , :delimiter => ',') %>
                    <% else %>
                        N/A
                    <% end %>
                  </td>
                  <td>
                    <% if lead.assigned_to.present? %>
                        <% magic = User.where(:id => lead.assigned_to).last %>
                        <% if magic.first_name.present? && magic.last_name.present? %>
                            <%= magic.first_name %> <%= magic.last_name %>
                        <% else %>
                            <%= magic.username %>
                        <% end %>
                    <% end %>
                  </td>
                  <td><%= lead.decorated_created_at %></td>
                  <td><%= stars_for(lead) %></td>
                  <!--<td><%# link_to('x', lead_path(lead), data: {:confirm => "Are you sure?"}, :method => :delete) %></td>-->
                  <!--<td><%# check_box_tag("convert[#{lead.id}]",1,false,class: "convertcheck") %></td>-->
                  <td><%= check_box_tag("contact_ids[]",lead.id,false,class: "deletecheck") %></td>
                </tr>
            <% end %>
        <% end %>
      </table>
      <% if current_user.admin? %>
          <%= submit_tag "Delete Selected", id: "delsubmit", class: "bulkbutton" %>
      <% end %>
  <% end %>
  <% if current_user.admin? %>
      <input value="Deselect All" type="submit" id="uncheckAll" class="bulkbutton" style="background-color:green;">
      <input value="Select All" type="submit" id="checkAll" class="bulkbutton">
  <% end %>
</div>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $('li > a').css('background-color','#466BB1');
    $('li > a').css('color','#eee');
    $('a[href$="leadcontacts"]').css('background-color','#e5e5e5');
    $('a[href$="leadcontacts"]').css('color','black');
    $('input:checkbox').prop('checked', false);
    $('#delsubmit').click(function() {
      return window.confirm("Are you sure?");
    });
    $("#checkAll").click(function(){
      $('input:checkbox').prop('checked', true);
    });
    $("#uncheckAll").click(function(){
      $('input:checkbox').prop('checked', false);
    });
    $('td').each(function(){
      if($(this).html()=="Partial"){
        $(this).css('background-color','red');
        $(this).css('color', 'white');
      }
      else if($(this).html()=="Full") {
        $(this).css('background-color', 'green');
        $(this).css('color','white');
      }
    })
  });
</script>
<% if !current_user.admin? %>
    <script type="text/javascript" charset="utf-8">
      $('#filters').hide();
    </script>
<% end %>
<br><br><br><br>
<div>
  <% if current_user.admin? %>
      <%# will_paginate @leads %>
  <% end %>
</div>

app/views/leadcontacts/new.html.erb
<div class="title">
  <span>
    New Lead
  </span>
  <%= link_to 'Back', '/leadcontacts' %>
</div>
<div class="remote">
  <%= simple_form_for @lead, url:leadcontacts_path do |f| %>
      <%= f.input :islead , :as => :hidden, input_html: { value: 'true'} %>
      <%= f.input :first_name %>
      <!--req-->
      <%= f.input :last_name %>
      <!--req-->
      <%= f.input :phone %>
      <%= f.input :email, input_html: { maxlength: 50 } %>
      <%= f.input :occupation %>
      <%= f.input :buysell %>
      <!--change to dropdown ^-->
      <%= f.input :assigned_to %>
      <!--change to dropdown ^-->
      <%= f.input :desireddeal %>
      <!--change to dropdown ^-->
      <%= f.input :address %>
      <%= f.input :unit %>
      <%= f.input :city %>
      <!--force capitalize^-->
      <%= f.input :postalcode %>
      <%= f.input :neighbourhood %>
      <!--force capitalize^-->
      <%= f.input :propertytype %>
      <!--change to dropdown^-->
      <%= f.input :price %>
      <%= f.input :buildingage %>
      <%= f.input :bedrooms %>
      <%= f.input :bathrooms %>
      <%= f.submit "Create Lead" %>
  <% end %>
</div>
<script type="text/javascript" charset="utf-8">
  $(function() {
    $('li > a').css('background-color', '#466BB1');
    $('li > a').css('color', '#eee');
    $('a[href$="leadcontacts"]').css('background-color', '#e5e5e5');
    $('a[href$="leadcontacts"]').css('color', 'black');
  })
</script>