config/routes.rb
Rails.application.routes.draw do

  get 'landing/buy1', to: 'landing#buy1'
  get 'landing/buy2', to: 'landing#buy2'
  get 'landing/buy3', to: 'landing#buy3'
  get 'landing/buy4', to: 'landing#buy4'
  get 'landing/sell1', to: 'landing#sell1'
  get 'landing/sell2', to: 'landing#sell2'
  get 'landing/sell3', to: 'landing#sell3'
  get 'landing/sell4', to: 'landing#sell4'
  post 'landing', action: :create1, controller: 'landing'
  post 'landing2', action: :create2, controller: 'landing'
  post 'landing3', action: :create3, controller: 'landing'
  post 'landing4', action: :create4, controller: 'landing'
  post 'landing5', action: :create5, controller: 'landing'
  post 'landing6', action: :create6, controller: 'landing'
  post 'landing7', action: :create7, controller: 'landing'
  post 'landing8', action: :create8, controller: 'landing'
  put 'landing/:id', to: 'landing#update1'
  put 'landing', to: 'landing#index'
  get 'landing', to: 'landing#index'
  get 'landing2', to: 'landing#index2'
  get 'landing3', to: 'landing#index3'
  get 'landing4', to: 'landing#index4'
  get 'landing5', to: 'landing#index5'
  get 'landing6', to: 'landing#index6'
  get 'landing7', to: 'landing#index7'
  get 'landing8', to: 'landing#index8'
  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendars', to: 'calendar#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'calendar#events', as: 'events', calendar_id: /[^\/]+/
  put 'tasks/:id', to: 'tasks#update1'
  get 'matches', to: 'matches#index'
  get 'contacts/buyers', to: 'contacts#buyersindex'
  get 'contacts/sellers', to: 'contacts#sellersindex'
  get 'contacts/closed', to: 'contacts#closed'
  put 'contacts/:id', action: 'convert', controller: 'contacts', as: 'convert_contact'
  get 'leads/buyers', to: 'leads#buyersindex'
  get 'leads/sellers', to: 'leads#sellersindex'
  get 'logout_session'  => 'authentications#destroy'
  get 'opportunities/buyers', to: 'opportunities#buyersindex'
  get 'opportunities/sellers', to: 'opportunities#sellersindex'
  get 'leadcontacts', to: 'leadcontacts#index'
  get '/leadcontacts/new', to: 'leadcontacts#new'
  post 'leadcontacts', action: :create, controller: 'leadcontacts'
  delete 'destroy_multiple_leadcontacts', action: 'destroy_multiple', controller: 'leadcontacts'

  resources :contacts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: %i[get post]
      get :redraw
      get :versions
      delete 'destroy_multiple'
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: %i[get post]
      get :redraw
      get :versions
      get :autocomplete_account_name
      delete 'destroy_multiple'
    end
    member do
      get :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put :attach
      match :promote, via: %i[patch put]
      put :reject
    end
  end
end

app/models/users/user.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
# == Schema Information
#
# Table name: users
#
#  id                  :integer         not null, primary key
#  username            :string(32)      default(""), not null
#  email               :string(64)      default(""), not null
#  first_name          :string(32)
#  last_name           :string(32)
#  title               :string(64)
#  company             :string(64)
#  alt_email           :string(64)
#  phone               :string(32)
#  mobile              :string(32)
#  aim                 :string(32)
#  yahoo               :string(32)
#  google              :string(32)
#  skype               :string(32)
#  password_hash       :string(255)     default(""), not null
#  password_salt       :string(255)     default(""), not null
#  persistence_token   :string(255)     default(""), not null
#  perishable_token    :string(255)     default(""), not null
#  last_login_at       :datetime
#  current_login_at    :datetime
#  last_login_ip       :string(255)
#  current_login_ip    :string(255)
#  login_count         :integer         default(0), not null
#  deleted_at          :datetime
#  created_at          :datetime
#  updated_at          :datetime
#  admin               :boolean         default(FALSE), not null
#  suspended_at        :datetime
#  single_access_token :string(255)
#

class User < ActiveRecord::Base
  has_one :avatar, as: :entity, dependent: :destroy  # Personal avatar.
  has_many :avatars                                         # As owner who uploaded it, ex. Contact avatar.
  has_many :comments, as: :commentable                   # As owner who created a comment.
  has_many :accounts
  has_many :campaigns
  has_many :leads
  has_many :contacts
  has_many :opportunities
  has_many :assigned_opportunities, class_name: 'Opportunity', foreign_key: 'assigned_to'
  has_many :permissions, dependent: :destroy
  has_many :preferences, dependent: :destroy
  has_many :lists
  has_and_belongs_to_many :groups

  has_paper_trail class_name: 'Version', ignore: [:perishable_token]

  scope :by_id, -> { order('id DESC') }
  scope :without, ->(user) { where('id != ?', user.id).by_name }
  scope :by_name, -> { order('first_name, last_name, email') }

  scope :text_search, ->(query) {
    query = query.gsub(/[^\w\s\-\.'\p{L}]/u, '').strip
    where('upper(username) LIKE upper(:s) OR upper(email) LIKE upper(:s) OR upper(first_name) LIKE upper(:s) OR upper(last_name) LIKE upper(:s)', s: "%#{query}%")
  }

  scope :my, -> { accessible_by(User.current_ability) }

  scope :have_assigned_opportunities, -> {
    joins("INNER JOIN opportunities ON users.id = opportunities.assigned_to")
        .where("opportunities.stage <> 'lost' AND opportunities.stage <> 'won'")
        .select('DISTINCT(users.id), users.*')
  }

  acts_as_authentic do |c|
    c.session_class = Authentication
    c.validates_uniqueness_of_login_field_options = { case_sensitive: false, message: :username_taken }
    c.validates_length_of_login_field_options     = { minimum: 1, message: :missing_username }
    c.validates_uniqueness_of_email_field_options = { message: :email_in_use }
    c.validates_length_of_password_field_options  = { minimum: 0, allow_blank: true, if: :require_password? }
    c.ignore_blank_passwords = true
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  # Store current user in the class so we could access it from the activity
  # observer without extra authentication query.
  cattr_accessor :current_user

  validates_presence_of :email, message: :missing_email

  #----------------------------------------------------------------------------
  def name
    first_name.blank? ? username : first_name
  end

  #----------------------------------------------------------------------------
  def full_name
    first_name.blank? && last_name.blank? ? email : "#{first_name} #{last_name}".strip
  end

  #----------------------------------------------------------------------------
  def suspended?
    suspended_at != nil
  end

  #----------------------------------------------------------------------------
  def awaits_approval?
    suspended? && login_count == 0 && Setting.user_signup == :needs_approval
  end

  #----------------------------------------------------------------------------
  def preference
    @preference ||= preferences.build
  end
  alias_method :pref, :preference

  #----------------------------------------------------------------------------
  def deliver_password_reset_instructions!
    reset_perishable_token!
    UserMailer.password_reset_instructions(self).deliver_now
  end

  # Override global I18n.locale if the user has individual local preference.
  #----------------------------------------------------------------------------
  def set_individual_locale
    I18n.locale = preference[:locale] if preference[:locale]
  end

  # Generate the value of single access token if it hasn't been set already.
  #----------------------------------------------------------------------------
  def set_single_access_token
    self.single_access_token ||= update_attribute(:single_access_token, Authlogic::Random.friendly_token)
  end

  def to_json(_options = nil)
    [name].to_json
  end

  def to_xml(_options = nil)
    [name].to_xml
  end

  def destroyable?
    check_if_current_user && !has_related_assets?
  end

  # Suspend newly created user if signup requires an approval.
  #----------------------------------------------------------------------------
  def check_if_needs_approval
    self.suspended_at = Time.now if Setting.user_signup == :needs_approval && !admin
  end

  # Prevent current user from deleting herself.
  #----------------------------------------------------------------------------
  def check_if_current_user
    User.current_user.nil? || User.current_user != self
  end

  # Prevent deleting a user unless she has no artifacts left.
  #----------------------------------------------------------------------------
  def has_related_assets?
    sum = %w[Account Campaign Lead Contact Opportunity Comment Task].detect do |asset|
      klass = asset.constantize

      asset != "Comment" && klass.assigned_to(self).exists? || klass.created_by(self).exists?
    end
    !sum.nil?
  end
  def self.options_for_select
    order('LOWER(name)').map { |e| [e.name, e.id] }
  end

  private

  # Define class methods
  #----------------------------------------------------------------------------
  class << self
    def current_ability
      Ability.new(User.current_user)
    end

    def can_signup?
      %i[allowed needs_approval].include? Setting.user_signup
    end
  end

  ActiveSupport.run_load_hooks(:fat_free_crm_user, self)
end

app/views/leads/_convert.html.haml
.remote
  = form_for(@lead, :url => promote_lead_path(@lead), :html => one_submit_only, :remote => true) do |f|
    = link_to_close convert_lead_path(@lead)
    = fields_for(@account) do |a|
      = a.hidden_field :user_id
      = a.hidden_field :access

      = error_messages_for :account, :opportunity, :object_name => t('lead')

      .section
        %table
          %tr
            %td
              .label.req #{t :assigned_to}:
              = user_select(:account, all_users, current_user)
    = render "leads/opportunity"
    = render "leads/convert_permissions"
    .buttonbar
      = f.submit t(:convert_lead)
      #{t :or}
      = link_to_cancel convert_lead_path(@lead)

app/views/leads/_index_long.html.haml
%li.highlight[lead]
  - if lead.status
    .strip{class: lead.status}= t lead.status
  - else
    .strip{style: "color: gray;"}= t :other

  %ul.tools
    - if can?(:update, lead)
      %li= link_to_edit(lead)

    - if %w(converted rejected).include?(lead.status)
      %li
        %font{ color: 'silver' }= t :convert
    - elsif can?(:update, lead)
      %li= link_to_convert(lead)

    - if lead.status == "rejected"
      %li
        %font{ color: 'silver' }= t :reject
    - elsif can?(:update, lead)
      %li= link_to_reject(lead)

    - if shown_on_landing_page?
      %li= link_to_discard(lead)

    - if can?(:destroy, lead)
      %li= link_to_delete(lead)

  .indent
    = link_to_if can?(:read, lead), lead.full_name(current_user.preference[:leads_naming]), lead
    %tt
      - if lead.company? && lead.title?
        = t(:works_at, job_title: lead.title, company: lead.company)
      - else
        = lead.company if lead.company?
        = lead.title if lead.title?
      - if lead.referred_by?
        &ndash;
        == #{t :referred_by_small} #{lead.referred_by}
      - if lead.buysell.present?
        == #{t "["}#{lead.buysell}#{t "]"}
      - if lead.leadstatus.present?
        == #{t "["}#{lead.leadstatus.capitalize}#{t " Lead]"}

    %dt
      - if can?(:read, lead)
        - if lead.email.present?
          = link_to_email(lead.email)
          |
        - if lead.phone.present?
          == #{t :phone_small}:
          %b= lead.phone
          |
        - if lead.mobile.present?
          == #{t :mobile_small}:
          %b= lead.mobile
          |
      = t(:added_ago, value: timeago(lead.created_at)).html_safe

    - if lead.tags.present?
      %dt
        .tags= tags_for_index(lead)

    = hook(:lead_bottom, self, lead: lead)

app/views/leads/_list.html.erb
<%# app/views/leads/_list.html.erb %>
<div id="filterrific_results">
  <style>
    #filter{
      width:100%;
    }
    #filter td,th{
      border:thin black solid;
    }
    #filter th{
      font-size:1.2em;
    }
    #filter td{
      text-align: right;
      padding-right:5px;
    }
    .tablecss td{
      text-align: center !important;
      font-size: 1.3em;
    }
    .bulkbutton{
      color:white;
      display:inline-block;
      float:right;
      padding: 5px;
      margin: 5px;
      border-radius: 4px;
      box-shadow: 2px 2px 3px #aaa;
    }
    #delsubmit{
      background-color: red;
    }
    #checkAll{
      background-color: dodgerblue;
    }
  </style>
  <div>
    <% if current_user.admin? %>
      <%= page_entries_info leads %>(s)
    <% end %>
    <!--<div class="bulkbutton" id="bulkconvert" style="background-color:green;">Convert Selected</div>-->
  </div>

  <br>
  <%= form_tag destroy_multiple_leads_path, method: :delete do %>
  <table class="tablecss" id="filter">
    <tr style="text-align: center;">
      <th>Lead Status</th>
      <th>Name</th>
      <th>Buyer/Seller</th>
      <th>Property Type</th>
      <th>Area</th>
      <th>Price</th>
      <th>Assigned To</th>
      <th>Registered at</th>
      <th>Rating</th>
      <th>Delete</th>
    </tr>
    <% leads.each do |lead| %>
      <% if current_user.admin? %>
        <tr>
          <td id="leadcolor"><%= lead.leadstatus.capitalize if lead.leadstatus.present? %></td>
          <td><%= link_to(lead.full_name, contact_path(lead)) %></td>
          <td><%= lead.buysell if lead.buysell.present? %></td>
          <td><%= lead.propertytype %></td>
          <td><%= lead.city %></td>
          <td>
            <% if lead.price.present? %>
                $<%= number_with_delimiter(lead.price , :delimiter => ',') %>
                <% else %>
                    N/A
            <% end %>
          </td>
          <td>
            <% if lead.assigned_to.present? %>
                <% magic = User.where(:id => lead.assigned_to).last %>
                <% if magic.first_name.present? && magic.last_name.present? %>
                    <%= magic.first_name %> <%= magic.last_name %>
                <% else %>
                    <%= magic.username %>
                <% end %>
            <% end %>
          </td>
          <td><%= lead.decorated_created_at %></td>
          <td><%= stars_for(lead) %></td>
          <!--<td><%# link_to('x', lead_path(lead), data: {:confirm => "Are you sure?"}, :method => :delete) %></td>-->
          <!--<td><%# check_box_tag("convert[#{lead.id}]",1,false,class: "convertcheck") %></td>-->
          <td><%= check_box_tag("lead_ids[]",lead.id,false,class: "deletecheck") %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
  <% if current_user.admin? %>
    <%= submit_tag "Delete Selected", id: "delsubmit", class: "bulkbutton" %>
  <% end %>
  <% end %>
  <% if current_user.admin? %>
  <input value="Deselect All" type="submit" id="uncheckAll" class="bulkbutton" style="background-color:green;">
  <input value="Select All" type="submit" id="checkAll" class="bulkbutton">
  <% end %>
</div>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $('input:checkbox').prop('checked', false);
    $('#delsubmit').click(function() {
      return window.confirm("Are you sure?");
    });
    $("#checkAll").click(function(){
      $('input:checkbox').prop('checked', true);
    });
    $("#uncheckAll").click(function(){
      $('input:checkbox').prop('checked', false);
    });
    $('td').each(function(){
      if($(this).html()=="Partial"){
        $(this).css('background-color','red');
      $(this).css('color', 'white');
      }
      else if($(this).html()=="Full") {
      $(this).css('background-color', 'green');
      $(this).css('color','white');
    }
    })
  });
</script>
<% if !current_user.admin? %>
    <script type="text/javascript" charset="utf-8">
      $('#filters').hide();
    </script>
<% end %>
<br><br><br><br>
<div>
  <% if current_user.admin? %>
    <%= will_paginate leads %>
  <% end %>
</div>

app/views/leads/_title_bar.html.haml
#confirm{ hidden }
.title_tools#menu
  - unless %w(converted rejected).include?(@lead.status)
    = link_to_inline(:convert_lead, convert_lead_path(@lead), :text => t(:convert)) + " | "
  = link_to_inline(:edit_lead, edit_lead_path(@lead), :text => t(:edit)) + " | "
  = link_to_function(t(:delete) + '?', confirm_delete(@lead))
.title_tools#buttons
  = view_buttons
.title#title
  = h(@lead.full_name)
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")

%div#convert_lead{ hidden }
%div#edit_lead{ hidden }

app/views/leads/buyersindex.html.erb
<%= styles_for :lead %>

<%= render 'entities/title_bar' %>

<div class="remote" id="create_lead" hidden="true"></div>

<%# app/views/leads/index.html.erb %>
  <style>
    .btncontact {
      background-color: rgba(0,0,0,0.75);
      /* Green */
      border: none;
      /*color: white !important;*/
      padding: 5px 20px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 12px;
      border-radius: 5px;
      box-shadow: 2px 2px 3px #aaa;
      font-weight: 600;
    }
  </style>

  <%#
  Filterrific adds the `form_for_filterrific` view helper:
  * adds dom id 'filterrific_filter'
  * applies javascript behaviors:
      * AJAX form submission on change
      * AJAX spinner while AJAX request is being processed
  * sets form_for options like :url, :method and input name prefix
%>
    <center>
      <div style="border: thin grey solid;box-shadow:2px 2px 3px #aaa;background-color: #eee">
        <br>
        <%= form_for_filterrific @filterrific do |f| %>
        <div style="display:inline-block;padding-left:10px">
          Search
          <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
            <%= f.text_field( :search_query, class: 'filterrific-periodically-observed' ) %>
          </div>
          <% if current_user.admin? %>
            <!--<div style="display:inline-block;padding-left:10px">-->
            <!--Assigned Realtor-->
            <%# f.select(
#               :with_assigned_to,
#               @filterrific.select_options[:with_assigned_to],
#               { include_blank: '- Any -' }
          ) %>
              <!--</div>-->
            <% end %>
            <!--<div style="display:inline-block;padding-left:10px">-->
            <!--Buyer/Seller-->
            <!--<%# f.select(-->
            <!--:with_buysell,-->
            <!--@filterrific.select_options[:with_buysell],-->
            <!--{ include_blank: '- All -'}-->
            <!--) %>-->
            <!--</div>-->
            <div style="display:inline-block;padding-left:10px">
              <%= f.text_field(:with_buysell, value: "Buyer", hidden: "true")%>
            </div>
            <div style="display:inline-block;padding-left:10px">
              Registered after
              <%= f.text_field(:with_created_at_gte, class: 'js-datepicker') %>
            </div>
            <div style="display:inline-block;padding-left:10px">
              Sort by
              <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
            </div>
            <br>
            <br>
            <div>

              <%= link_to( 'Reset Filters', reset_filterrific_url, {:style=>' color: white !important; padding: 8px; margin-right: 2%; background-color: rgba(0,0,0,0.75); border-radius: 5px;'} ) %>
              <%# add an automated spinner to your form when the list is refreshed %>
                <%= render_filterrific_spinner %>
              </div>
              <%# add an automated spinner to your form when the list is refreshed %>
                <%= render_filterrific_spinner %>
              <% end %>
              <br>
            </div>
          </center>
          <script>
            $(function () {
              $(".js-datepicker").datepicker({dateFormat: 'yy-mm-dd'});
            });
          </script>
          <br>
          <div style="float: right; padding-right: 1%;">
            <span class="btncontact"><%= link_to leads_path do %>
              <span style="color: white !important;">All Leads</span><% end %>
          </span>
          <span class="btncontact"><%= link_to leads_buyers_path do %>
            <span style="color: white !important;">Buyers</span><% end %>
        </span>
        <span class="btncontact"><%= link_to leads_sellers_path do %>
          <span style="color: white !important;">Sellers</span><% end %>
      </span>
    </div>
    <br>
    <div id="llist">
      <%= render( partial: 'leads/list', locals: { leads: @leads } ) %>
    </div>

app/views/leads/index.html.erb
<%= styles_for :lead %>

<%= render 'entities/title_bar' %>
<script type="text/javascript" charset="utf-8">
 $(function(){
   $('.create_asset > a').attr('data-remote','false').attr('href','/leads/new');
 });
</script>

<div class="remote" id="create_lead" hidden="true"></div>

<%# app/views/leads/index.html.erb %>
  <style>
    .btncontact {
      background-color: rgba(0,0,0,0.75);
      /* Green */
      border: none;
      /*color: white !important;*/
      padding: 5px 20px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 12px;
      border-radius: 5px;
      box-shadow: 2px 2px 3px #aaa;
      font-weight: 600;
    }
  </style>

  <%#
  Filterrific adds the `form_for_filterrific` view helper:
  * adds dom id 'filterrific_filter'
  * applies javascript behaviors:
      * AJAX form submission on change
      * AJAX spinner while AJAX request is being processed
  * sets form_for options like :url, :method and input name prefix
%>
    <center>
      <div style="border: thin grey solid;box-shadow:2px 2px 3px #aaa;background-color: #eee">
        <!-- <h3 style="padding-left:10px;padding-top: 8px">Filter</h3> -->
        <br>
        <%= form_for_filterrific @filterrific do |f| %>
        <div style="display:inline-block;padding-left:10px">
          Search
          <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
            <%= f.text_field( :search_query, class: 'filterrific-periodically-observed' ) %>
          </div>
          <% if current_user.admin? %>
            <!--<div style="display:inline-block;padding-left:10px">-->
            <!--Assigned Realtor-->
            <%# f.select(
#               :with_assigned_to,
#               @filterrific.select_options[:with_assigned_to],
#               { include_blank: '- Any -' }
          ) %>
              <!--</div>-->
            <% end %>
            <div style="display:inline-block;padding-left:10px">
              Lead Status
              <%= f.select( :with_buysell, @filterrific.select_options[:with_buysell], { include_blank: '- All -'} ) %>
            </div>
            <div style="display:inline-block;padding-left:10px">
              Registered after
              <%= f.text_field(:with_created_at_gte, class: 'js-datepicker') %>
            </div>
            <div style="display:inline-block;padding-left:10px">
              Sort by
              <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
            </div>
            <br>
            <br>
            <div>
              <%= link_to( 'Reset Filters', reset_filterrific_url, {:style=>' color: white !important; padding: 8px; margin-right: 2%; background-color: rgba(0,0,0,0.75); border-radius: 5px;'} ) %>

              <%# add an automated spinner to your form when the list is refreshed %>
                <%= render_filterrific_spinner %>
              <% end %>
            </div>
            <br>
          </div>
        </center>
        <script>
          $(function () {
            $(".js-datepicker").datepicker({dateFormat: 'yy-mm-dd'});
          });
        </script>
        <br>
        <div style="float: right; padding-right: 1%;">
          <span class="btncontact"><%= link_to leads_path do %>
            <span style="color: white !important;">All Leads</span><% end %>
        </span>
        <span class="btncontact"><%= link_to leads_buyers_path do %>
          <span style="color: white !important;">Buyers</span><% end %>
      </span>
      <span class="btncontact"><%= link_to leads_sellers_path do %>
        <span style="color: white !important;">Sellers</span><% end %>
    </span>
  </div>
  <br>
  <div id="llist">
    <%= render( partial: 'leads/list', locals: { leads: @leads } ) %>
  </div>

app/views/leads/sellersindex.html.erb
<%= styles_for :lead %>

<%= render 'entities/title_bar' %>

<div class="remote" id="create_lead" hidden="true"></div>

<%# app/views/leads/index.html.erb %>
  <style>
    .btncontact {
      background-color: rgba(0,0,0,0.75);
      /* Green */
      border: none;
      /*color: white !important;*/
      padding: 5px 20px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 12px;
      border-radius: 5px;
      box-shadow: 2px 2px 3px #aaa;
      font-weight: 600;
    }
  </style>

  <%#
  Filterrific adds the `form_for_filterrific` view helper:
  * adds dom id 'filterrific_filter'
  * applies javascript behaviors:
      * AJAX form submission on change
      * AJAX spinner while AJAX request is being processed
  * sets form_for options like :url, :method and input name prefix
%>
    <center>
      <div style="border: thin grey solid;box-shadow:2px 2px 3px #aaa;background-color: #eee">
        <br>
        <%= form_for_filterrific @filterrific do |f| %>
        <div style="display:inline-block;padding-left:10px">
          Search
          <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
            <%= f.text_field( :search_query, class: 'filterrific-periodically-observed' ) %>
          </div>
          <% if current_user.admin? %>
            <!--<div style="display:inline-block;padding-left:10px">-->
            <!--Assigned Realtor-->
            <%# f.select(
#               :with_assigned_to,
#               @filterrific.select_options[:with_assigned_to],
#               { include_blank: '- Any -' }
          ) %>
              <!--</div>-->
            <% end %>
            <!--<div style="display:inline-block;padding-left:10px">-->
            <!--Buyer/Seller-->
            <!--<%# f.select(-->
            <!--:with_buysell,-->
            <!--@filterrific.select_options[:with_buysell],-->
            <!--{ include_blank: '- All -'}-->
            <!--) %>-->
            <!--</div>-->
            <div style="display:inline-block;padding-left:10px">
              <%= f.text_field(:with_buysell, value: "Seller", hidden: "true")%>
            </div>
            <div style="display:inline-block;padding-left:10px">
              Registered after
              <%= f.text_field(:with_created_at_gte, class: 'js-datepicker') %>
            </div>
            <div style="display:inline-block;padding-left:10px">
              Sort by
              <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
            </div>
            <br>
            <br>
            <div>

              <%= link_to( 'Reset Filters', reset_filterrific_url, {:style=>' color: white !important; padding: 8px; margin-right: 2%; background-color: rgba(0,0,0,0.75); border-radius: 5px;'} ) %>
              <%# add an automated spinner to your form when the list is refreshed %>
                <%= render_filterrific_spinner %>
              </div>

              <%# add an automated spinner to your form when the list is refreshed %>
                <%= render_filterrific_spinner %>
              <% end %>
              <br>
            </div>
          </center>
          <script>
            $(function () {
              $(".js-datepicker").datepicker({dateFormat: 'yy-mm-dd'});
            });
          </script>
          <br>
          <div style="float: right; padding-right: 1%;">
            <span class="btncontact"><%= link_to leads_path do %>
              <span style="color: white !important;">All Leads</span><% end %>
          </span>
          <span class="btncontact"><%= link_to leads_buyers_path do %>
            <span style="color: white !important;">Buyers</span><% end %>
        </span>
        <span class="btncontact"><%= link_to leads_sellers_path do %>
          <span style="color: white !important;">Sellers</span><% end %>
      </span>
    </div>
    <br>
    <div id="llist">
      <%= render( partial: 'leads/list', locals: { leads: @leads } ) %>
    </div>